name: infojobs_agent
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pip
    - pip:
          # FastAPI y servidor
          - fastapi
          - uvicorn[standard]
          - python-multipart

          # Utilidades web
          - requests
          - python-dotenv

          # IA y LangChain
          - openai
          - langchain>=0.3
          - langchain-core
          - langchain-openai
          - langchain-community

          # Validación
          - pydantic
          - pydantic-core

          # Base de datos
          - psycopg2-binary

          # Utilidades
          - sniffio
